name: check-projects
on:
  pull_request:
    branches:
      - master

jobs:
  check-matsim-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Checkout Baseline
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: spotbugs-baseline
          persist-credentials: false

      - name: Checkout Matsim-libs
        uses: actions/checkout@v2
        with:
          repository: 'matsim-org/matsim-libs'
          ref: 'matsim-12.0'
          path: matsim-libs
          persist-credentials: false

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.x'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Quick-Build new Spotbugs
        run: ./gradlew installDist --no-daemon 

      - name: Quick-Build baseline Spotbugs
        run: ./gradlew installDist --no-daemon 
        working-directory: spotbugs-baseline

      - name: Build Matsim-libs
        run: mvn -pl matsim compile
        working-directory: matsim-libs

      - name: Check Matsim-libs with baseline
        run: |
          baseline_start="$(date +%s)"
          spotbugs-baseline/spotbugs/build/install/spotbugs/bin/spotbugs -textui \
            matsim-libs/matsim/target/classes 2>/dev/null | tee results_matsim_baseline 
          baseline_end="$(date +%s)"
          echo "$((baseline_end - baseline_start))" > baseline_time_matsim

      - name: Check Matsim-libs with new
        run: |
          new_start="$(date +%s)"
          spotbugs/build/install/spotbugs/bin/spotbugs -textui \
            matsim-libs/matsim/target/classes 2>/dev/null | tee results_matsim_new 
          new_end="$(date +%s)"
          echo "$((new_end - new_start))" > new_time_matsim

      - name: Check Matsim-libs diff
        id: report-diff
        run: |
          diff -u results_matsim_baseline results_matsim_new | tee diff_matsim

      - name: Package artifacts
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          mv diff_matsim pr/
          mv baseline_time_matsim pr/
          mv new_time_matsim pr/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
