name: check-projects-comment

on:
  workflow_run:
    workflows: ['check-projects']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3
        with:
          script: |
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            })
            const matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == 'pr'
            })[0]
            const download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            })
            const fs = require('fs')
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data))

      - run: unzip pr.zip

      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const issue_number = Number(fs.readFileSync('./NR'))
            const baseline_time_matsim = Number(fs.readFileSync('./baseline_time_matsim'))
            const new_time_matsim = Number(fs.readFileSync('./new_time_matsim'))

            const diff_matsim = fs.readFileSync('./diff_matsim')

            const body =
            `matsim-libs
               baseline time: ${baseline_time_matsim}s
               new time: ${new_time_matsim}s
               results diff: ${diff_matsim ? '\n```' + diff_matsim + '```' : '-'}
            `

            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body,
            })
